export const QUESTIONS_LOT1: Record<string, { module: string; questions: { q: string; d?: string; p?: string }[] }[]> = {
  outil81: [
    { module: "Cuisine et equipements", questions: [
      { q: "Les equipements de cuisine (fours, friteuses, plaques) sont-ils regulierement entretenus et verifies ?", d: "Risque de dysfonctionnement pouvant entrainer brulures ou incendie", p: "Mettre en place un plan de maintenance preventive avec cahier de suivi des interventions" },
      { q: "Les dispositifs de securite des machines de cuisine (coupe-legumes, trancheurs, batteurs) sont-ils en place et fonctionnels ?", d: "Risque de coupures graves ou d'amputation par les parties mobiles", p: "Verifier quotidiennement les carters de protection et interdire l'utilisation sans dispositifs de securite" },
      { q: "Les hottes d'aspiration et les systemes de ventilation de la cuisine sont-ils nettoyes et entretenus periodiquement ?", d: "Accumulation de graisses pouvant provoquer un incendie ou une mauvaise qualite de l'air", p: "Planifier le nettoyage des hottes chaque semaine et la verification des filtres chaque mois" },
      { q: "Les zones de cuisson sont-elles equipees de moyens d'extinction adaptes (couverture anti-feu, extincteur) ?", d: "Risque de propagation rapide d'un feu de graisse ou d'huile", p: "Installer une couverture anti-feu et un extincteur adapte aux feux de classe F a proximite des friteuses" },
      { q: "Les ustensiles et equipements de cuisine sont-ils ranges de maniere ordonnee apres utilisation ?", d: "Risque de chute d'objets ou de blessures par des outils mal ranges", p: "Definir des emplacements de rangement pour chaque ustensile et sensibiliser le personnel au rangement systematique" },
      { q: "Les branchements electriques des equipements de cuisine sont-ils proteges contre les projections d'eau ?", d: "Risque d'electrocution par contact eau-electricite", p: "Utiliser des prises etanches IP44 minimum et eloigner les branchements des points d'eau" },
    ]},
    { module: "Sols et deplacements", questions: [
      { q: "Les sols de la cuisine et de la salle sont-ils traites avec un revetement antiderapant ?", d: "Risque de glissade sur sols mouilles ou gras", p: "Installer des revetements antiderapants certifies et remplacer les zones usees" },
      { q: "Un protocole de nettoyage immediat des sols en cas de renversement de liquide est-il en place ?", d: "Risque de chute de plain-pied pour le personnel et les clients", p: "Former le personnel au nettoyage immediat et mettre a disposition des kits de nettoyage rapide" },
      { q: "Les zones de circulation entre la cuisine et la salle sont-elles degagees et balisees ?", d: "Risque de collision entre serveurs portant des plats chauds", p: "Definir un sens de circulation et installer des portes battantes avec hublot de vision" },
      { q: "Les escaliers et marches sont-ils equipes de nez de marche antiderapants et de mains courantes ?", d: "Risque de chute dans les escaliers", p: "Poser des bandes antiderapantes sur chaque marche et verifier la solidite des mains courantes" },
      { q: "Les tapis et caillebotis sont-ils en bon etat et correctement fixes au sol ?", d: "Risque de trebuchement sur des tapis decoles ou deformes", p: "Remplacer les tapis uses et fixer les bords avec des profils de maintien" },
    ]},
    { module: "Manutention et stockage", questions: [
      { q: "Les salaries ont-ils ete formes aux gestes et postures pour le port de charges en cuisine et en salle ?", d: "Risque de troubles musculosquelettiques (TMS) du dos et des epaules", p: "Organiser une formation gestes et postures annuelle et mettre a disposition des aides a la manutention" },
      { q: "Les livraisons de marchandises sont-elles organisees pour limiter le port de charges lourdes ?", d: "Risque de lombalgies et de blessures lors du dechargement", p: "Utiliser des chariots et diables pour le transport et limiter le poids des colis a 15 kg" },
      { q: "Les rayonnages de stockage sont-ils stables, fixes au mur et charges en respectant les limites de poids ?", d: "Risque d'effondrement des etageres et de chute d'objets", p: "Fixer les rayonnages au mur, placer les charges lourdes en bas et afficher les charges maximales" },
      { q: "Les chambres froides sont-elles equipees d'un systeme d'ouverture interieure de securite ?", d: "Risque d'enfermement accidentel dans la chambre froide", p: "Verifier mensuellement le bon fonctionnement du systeme d'ouverture interieure et de l'alarme" },
      { q: "Les zones de stockage sont-elles organisees selon le principe FIFO (premier entre, premier sorti) ?", d: "Risque de manipulation excessive des denrees et de chutes lors de la recherche de produits", p: "Mettre en place un systeme d'etiquetage par date et organiser les etageres pour un acces facile" },
    ]},
    { module: "Risques chimiques et allergenes", questions: [
      { q: "Les produits de nettoyage et de desinfection sont-ils stockes dans un local dedie et ventile ?", d: "Risque d'intoxication par inhalation de vapeurs chimiques ou de melange de produits incompatibles", p: "Amenager un local de stockage ventile avec bac de retention et afficher les consignes de securite" },
      { q: "Les fiches de donnees de securite (FDS) des produits chimiques sont-elles accessibles au personnel ?", d: "Meconnaissance des risques lies aux produits manipules", p: "Classer les FDS dans un classeur accessible et former le personnel a leur lecture" },
      { q: "Les salaries portent-ils des gants et des lunettes de protection lors de l'utilisation de produits chimiques ?", d: "Risque de brulures chimiques de la peau et des yeux", p: "Fournir des EPI adaptes (gants nitrile, lunettes) et former a leur utilisation correcte" },
      { q: "Les allergenes presents dans les plats sont-ils identifies et communiques aux clients et au personnel ?", d: "Risque de reaction allergique grave chez les clients ou le personnel", p: "Afficher la liste des 14 allergenes reglementaires et former le personnel a la gestion des allergenes" },
      { q: "Un protocole est-il en place pour eviter les contaminations croisees entre allergenes en cuisine ?", d: "Risque de presence involontaire d'allergenes dans un plat", p: "Utiliser des ustensiles dedies, des zones de preparation separees et des procedures de nettoyage specifiques" },
    ]},
    { module: "Risques de brulures et coupures", questions: [
      { q: "Les salaries disposent-ils de gants anti-chaleur pour manipuler les plats et recipients chauds ?", d: "Risque de brulures thermiques aux mains et aux avant-bras", p: "Mettre a disposition des gants anti-chaleur en nombre suffisant et les remplacer des qu'ils sont uses" },
      { q: "Les friteuses sont-elles equipees de couvercles de securite et de thermostats fonctionnels ?", d: "Risque de brulures par projection d'huile bouillante", p: "Verifier le thermostat avant chaque service et former le personnel aux procedures de vidange securisee" },
      { q: "Les couteaux et outils tranchants sont-ils entretenus et ranges dans des supports adaptes ?", d: "Risque de coupures par des lames emousees necessitant plus de force ou par des couteaux mal ranges", p: "Utiliser des porte-couteaux magnetiques ou des blocs de rangement et affuter regulierement les lames" },
      { q: "Les salaries ont-ils recu une formation a l'utilisation securisee des trancheurs et coupe-legumes ?", d: "Risque de coupures graves lors de l'utilisation de machines tranchantes", p: "Former chaque nouvel employe a l'utilisation des machines et afficher les consignes de securite" },
      { q: "Des gants anti-coupure sont-ils fournis pour les operations de decoupe manuelle ?", d: "Risque de coupures profondes lors du tranchage de viandes ou legumes", p: "Fournir des gants en maille metallique ou en fibres anti-coupure et en imposer le port" },
      { q: "Les becs verseurs des casseroles sont-ils orientes vers l'interieur du plan de cuisson ?", d: "Risque de renversement de liquides brulants et de brulures", p: "Former le personnel a orienter les manches vers l'interieur et a ne pas remplir les recipients au-dela des 2/3" },
    ]},
    { module: "Organisation du travail et RPS", questions: [
      { q: "Les horaires de travail respectent-ils les temps de repos minimaux entre deux services ?", d: "Risque de fatigue excessive et d'erreurs liees au manque de repos", p: "Planifier les horaires en respectant 11 heures de repos minimum entre deux journees de travail" },
      { q: "Les salaries ont-ils la possibilite de prendre des pauses regulieres pendant les periodes de forte activite ?", d: "Risque d'epuisement physique et de stress", p: "Organiser un roulement de pauses et amenager un espace de repos calme" },
      { q: "Les situations de violence verbale ou de harcelement de la part des clients sont-elles prises en charge ?", d: "Risque de souffrance psychologique et de burn-out", p: "Mettre en place un protocole de gestion des incivilites et un soutien psychologique pour les salaries" },
      { q: "La charge de travail est-elle repartie equitablement entre les membres de l'equipe ?", d: "Risque de surcharge pour certains salaries et de tensions dans l'equipe", p: "Realiser des entretiens reguliers sur la charge de travail et ajuster les effectifs en fonction de l'activite" },
      { q: "Les nouveaux salaries beneficient-ils d'un accompagnement et d'une formation a la prise de poste ?", d: "Risque d'accidents par meconnaissance des procedures et des equipements", p: "Mettre en place un parcours d'integration avec un tuteur et un livret d'accueil securite" },
    ]},
    { module: "Incendie et securite", questions: [
      { q: "Les extincteurs sont-ils verifies annuellement et accessibles dans toutes les zones de l'etablissement ?", d: "Risque de ne pas pouvoir intervenir rapidement en cas de depart de feu", p: "Faire verifier les extincteurs chaque annee par un organisme agree et afficher leur emplacement" },
      { q: "Les issues de secours sont-elles degagees, signalees et eclairees en permanence ?", d: "Risque de blocage lors d'une evacuation d'urgence", p: "Verifier quotidiennement le degagement des issues et le fonctionnement des blocs autonomes d'eclairage" },
      { q: "Des exercices d'evacuation sont-ils organises au moins deux fois par an ?", d: "Risque de panique et de desorganisation en cas d'incendie reel", p: "Planifier deux exercices par an, former les serre-files et analyser les retours d'experience" },
      { q: "Le systeme de detection incendie est-il controle et entretenu regulierement ?", d: "Risque de non-detection d'un depart de feu", p: "Faire verifier le systeme de detection chaque trimestre et remplacer les detecteurs defaillants" },
      { q: "Les consignes d'evacuation sont-elles affichees et connues de tout le personnel ?", d: "Risque de mauvaise reaction en cas d'alarme incendie", p: "Afficher les plans d'evacuation dans chaque zone et organiser des sessions de rappel des consignes" },
    ]},
    { module: "Hygiene et risques biologiques", questions: [
      { q: "Les salaries respectent-ils les regles de lavage des mains avant et apres chaque manipulation d'aliments ?", d: "Risque de contamination biologique des aliments et de toxi-infections alimentaires", p: "Installer des lave-mains a commande non manuelle et afficher les consignes de lavage des mains" },
      { q: "Les temperatures des chambres froides et des equipements de conservation sont-elles controlees et enregistrees ?", d: "Risque de proliferation bacterienne en cas de rupture de la chaine du froid", p: "Mettre en place des enregistreurs de temperature avec alarme et controler les releves deux fois par jour" },
      { q: "Les poubelles et conteneurs a dechets sont-ils vides regulierement et nettoyes quotidiennement ?", d: "Risque de proliferation de bacteries, d'insectes et de nuisibles", p: "Vider les poubelles a chaque service et les nettoyer-desinfecter quotidiennement" },
      { q: "Un plan de nettoyage et de desinfection des surfaces de travail est-il defini et applique ?", d: "Risque de contamination croisee entre les aliments", p: "Elaborer un plan de nettoyage detaille avec frequences, produits et responsables" },
      { q: "Les salaries disposent-ils de vestiaires et de tenues de travail propres et adaptees ?", d: "Risque de contamination des aliments par des vetements de ville", p: "Fournir des tenues de travail lavees regulierement et amenager des vestiaires separes" },
    ]},
  ],

  outil69: [
    { module: "Amenagement du poste de travail", questions: [
      { q: "Le bureau dispose-t-il d'une surface de travail suffisante pour accueillir l'ecran, le clavier et les documents ?", d: "Risque de postures contraignantes par manque d'espace de travail", p: "Prevoir un plan de travail d'au moins 120 x 80 cm et degager l'espace sous le bureau" },
      { q: "Le siege de bureau est-il reglable en hauteur, profondeur d'assise et inclinaison du dossier ?", d: "Risque de lombalgies et de douleurs cervicales par un siege inadapte", p: "Fournir des sieges ergonomiques reglables et former les salaries a leur reglage" },
      { q: "Le poste de travail est-il organise pour limiter les rotations et torsions du tronc ?", d: "Risque de TMS du rachis par des mouvements repetes de torsion", p: "Placer les documents et le telephone a portee de main et centrer l'ecran face a l'utilisateur" },
      { q: "Les cables electriques et informatiques sont-ils ranges et proteges pour eviter les risques de chute ?", d: "Risque de trebuchement sur des cables au sol", p: "Utiliser des goulottes, des passe-cables et des enrouleurs pour organiser le cablage" },
      { q: "Les espaces de circulation dans les bureaux sont-ils degages et d'une largeur suffisante ?", d: "Risque de chute ou de collision dans les zones de passage", p: "Maintenir des largeurs de passage d'au moins 80 cm et ne pas encombrer les couloirs" },
    ]},
    { module: "Ecran et eclairage", questions: [
      { q: "L'ecran est-il positionne a une distance de 50 a 70 cm des yeux et le bord superieur a hauteur des yeux ?", d: "Risque de fatigue visuelle et de douleurs cervicales", p: "Regler la hauteur de l'ecran avec un support ou un bras articule et verifier la distance" },
      { q: "L'eclairage du poste de travail est-il suffisant et sans reflets genants sur l'ecran ?", d: "Risque de fatigue visuelle par un eclairage inadapte ou des reflets", p: "Positionner l'ecran perpendiculairement aux fenetres et installer un eclairage d'appoint si necessaire" },
      { q: "Les fenetres sont-elles equipees de stores ou de filtres anti-reflets ?", d: "Risque d'eblouissement et de reflets sur l'ecran", p: "Installer des stores a lamelles orientables et des films anti-reflets sur les fenetres" },
      { q: "Les salaries effectuent-ils des pauses visuelles regulieres (regle des 20-20-20) ?", d: "Risque de secheresse oculaire et de fatigue visuelle", p: "Encourager une pause de 20 secondes toutes les 20 minutes en regardant a 20 pieds (6 metres)" },
      { q: "Les ecrans sont-ils de bonne qualite, sans scintillement, avec une resolution et un contraste adaptes ?", d: "Risque de fatigue visuelle par un ecran de mauvaise qualite", p: "Remplacer les ecrans anciens par des ecrans LED anti-scintillement et regler la luminosite" },
    ]},
    { module: "Ergonomie et postures", questions: [
      { q: "Les salaries ont-ils recu une formation sur les bonnes postures de travail sur ecran ?", d: "Risque de TMS par des postures statiques prolongees et inadaptees", p: "Organiser des sessions de sensibilisation a l'ergonomie et proposer des evaluations individuelles" },
      { q: "Un repose-pieds est-il mis a disposition des salaries dont les pieds ne reposent pas a plat au sol ?", d: "Risque de troubles circulatoires et de douleurs lombaires", p: "Fournir des repose-pieds reglables en hauteur et en inclinaison" },
      { q: "Les salaries alternent-ils entre position assise et position debout au cours de la journee ?", d: "Risque de sedentarite excessive et de pathologies associees", p: "Proposer des bureaux reglables en hauteur et encourager les micro-pauses actives" },
      { q: "Le clavier et la souris sont-ils positionnes de maniere a garder les poignets droits et les coudes a 90 degres ?", d: "Risque de syndrome du canal carpien et de tendinites", p: "Utiliser un clavier et une souris ergonomiques et installer un repose-poignets" },
      { q: "Les salaries travaillant sur ordinateur portable disposent-ils d'un clavier et d'un ecran externes ?", d: "Risque de postures penalisantes avec un ecran trop bas et un clavier trop etroit", p: "Fournir un support pour ordinateur portable, un clavier et une souris externes" },
    ]},
    { module: "Ambiance thermique et qualite de l'air", questions: [
      { q: "La temperature des bureaux est-elle maintenue entre 20 et 24 degres en hiver et en dessous de 26 degres en ete ?", d: "Risque d'inconfort thermique affectant la concentration et la sante", p: "Installer des thermometres dans chaque bureau et regler la climatisation de maniere adequate" },
      { q: "La ventilation des locaux est-elle suffisante pour assurer un renouvellement d'air adequat ?", d: "Risque de concentration de CO2 et de polluants interieurs", p: "Entretenir regulierement le systeme de ventilation et aerer les bureaux au moins 10 minutes par jour" },
      { q: "Les imprimantes et photocopieurs sont-ils places dans des locaux separes et ventiles ?", d: "Risque d'emission de particules fines et d'ozone dans l'air des bureaux", p: "Installer les imprimantes dans un local dedie avec ventilation et limiter les impressions" },
      { q: "Le taux d'humidite des bureaux est-il maintenu entre 40 et 60 % ?", d: "Risque de secheresse des muqueuses ou de proliferation de moisissures", p: "Utiliser des humidificateurs ou deshumidificateurs selon les besoins et mesurer l'hygrometrie" },
    ]},
    { module: "Risques electriques", questions: [
      { q: "Les installations electriques des bureaux sont-elles verifiees periodiquement par un organisme agree ?", d: "Risque d'electrocution ou d'incendie d'origine electrique", p: "Faire realiser une verification annuelle par un organisme agree et corriger les anomalies" },
      { q: "Les multiprises sont-elles utilisees de maniere raisonnee sans surcharge ni branchement en cascade ?", d: "Risque de surchauffe et d'incendie par surcharge electrique", p: "Limiter le nombre d'appareils par multiprise et interdire le branchement en cascade" },
      { q: "Les prises electriques et les interrupteurs sont-ils en bon etat, sans fil denude ni boitier casse ?", d: "Risque de contact direct avec des conducteurs sous tension", p: "Signaler et faire reparer immediatement toute prise ou interrupteur endommage" },
      { q: "Les appareils electriques personnels (chauffages d'appoint, bouilloires) sont-ils reglementes dans les bureaux ?", d: "Risque de surcharge electrique et d'incendie", p: "Etablir une charte sur l'utilisation des appareils personnels et fournir des equipements collectifs" },
    ]},
    { module: "Risques psychosociaux", questions: [
      { q: "Les salaries disposent-ils de marges de manoeuvre suffisantes dans l'organisation de leur travail ?", d: "Risque de stress et de perte de sens au travail", p: "Favoriser l'autonomie dans l'organisation des taches et consulter les salaries sur les changements" },
      { q: "Les objectifs fixes aux salaries sont-ils realistes et clairement definis ?", d: "Risque de surcharge mentale et de demotivation", p: "Definir les objectifs en concertation avec les salaries et les reviser regulierement" },
      { q: "Un dispositif d'ecoute et d'accompagnement des salaries en difficulte est-il en place ?", d: "Risque de souffrance psychologique non detectee", p: "Mettre en place une cellule d'ecoute et former les managers a la detection des signaux faibles" },
      { q: "Les interruptions frequentes (emails, reunions, sollicitations) sont-elles gerees pour preserver la concentration ?", d: "Risque de surcharge cognitive et de stress", p: "Instaurer des plages horaires sans interruption et limiter le nombre de reunions quotidiennes" },
      { q: "Le teletravail est-il encadre avec des regles claires sur les horaires et le droit a la deconnexion ?", d: "Risque d'isolement social et de difficulte a separer vie professionnelle et vie privee", p: "Definir une charte du teletravail incluant le droit a la deconnexion et des echanges reguliers" },
    ]},
    { module: "Incendie et evacuation", questions: [
      { q: "Les plans d'evacuation sont-ils affiches a chaque etage et les issues de secours clairement signalees ?", d: "Risque de desorientation lors d'une evacuation d'urgence", p: "Afficher les plans d'evacuation conformes et verifier la signalisation des issues de secours" },
      { q: "Les exercices d'evacuation sont-ils realises au moins une fois par an ?", d: "Risque de mauvaise gestion d'une evacuation en situation reelle", p: "Organiser un exercice annuel minimum, designar des guides et serre-files et faire un debriefing" },
      { q: "Les extincteurs sont-ils accessibles, visibles et adaptes aux types de feux possibles ?", d: "Risque de ne pas pouvoir eteindre un debut d'incendie", p: "Installer des extincteurs tous les 200 m2 et former les salaries a leur utilisation" },
      { q: "Les portes coupe-feu sont-elles en bon etat et non bloquees en position ouverte ?", d: "Risque de propagation rapide du feu entre les locaux", p: "Verifier trimestriellement le bon fonctionnement des portes coupe-feu et interdire leur blocage" },
    ]},
    { module: "Organisation et management", questions: [
      { q: "Le document unique d'evaluation des risques professionnels est-il mis a jour au moins une fois par an ?", d: "Non-conformite reglementaire et meconnaissance des risques actuels", p: "Planifier la mise a jour annuelle du DUERP en associant les salaries et le CSE" },
      { q: "Les salaries sont-ils informes et formes aux risques specifiques de leur poste de travail ?", d: "Risque d'accident par meconnaissance des dangers", p: "Organiser des formations securite a l'embauche et des rappels annuels pour chaque poste" },
      { q: "Les accidents du travail et les presqu'accidents sont-ils systematiquement analyses ?", d: "Risque de repetition des accidents par absence de retour d'experience", p: "Mettre en place un systeme de signalement et d'analyse des accidents et presqu'accidents" },
      { q: "Les managers sont-ils formes a la prevention des risques et a la detection des situations de mal-etre ?", d: "Risque de non-detection des situations dangereuses ou de souffrance au travail", p: "Former les managers a la prevention des risques et aux entretiens de suivi des salaries" },
    ]},
  ],

  outil75: [
    { module: "Produits chimiques et cosmetiques", questions: [
      { q: "Les fiches de donnees de securite des produits de coloration, decoloration et permanente sont-elles disponibles et a jour ?", d: "Risque d'exposition a des substances chimiques dangereuses (ammoniac, persulfates, PPD)", p: "Classer les FDS dans un classeur accessible au salon et les mettre a jour a chaque changement de produit" },
      { q: "Les salaries portent-ils des gants a usage unique adaptes lors de l'application de produits colorants ?", d: "Risque de dermatite de contact et d'allergie cutanee", p: "Fournir des gants en nitrile adaptes a la taille de chaque coiffeur et en imposer le port systematique" },
      { q: "Les produits de decoloration sont-ils prepares dans un espace ventile avec un equipement de protection ?", d: "Risque d'inhalation de poudre decolorante et de persulfates", p: "Installer un poste de preparation sous aspiration et utiliser des masques FFP2 lors du melange" },
      { q: "Les produits chimiques sont-ils stockes dans une armoire dediee, fermee et ventilee ?", d: "Risque de melange accidentel de produits incompatibles", p: "Amenager une armoire de stockage ventilee avec bac de retention et etiquetage clair" },
      { q: "Les salaries sont-ils formes aux risques lies aux produits capillaires qu'ils manipulent ?", d: "Risque d'utilisation incorrecte entrainant des reactions cutanees ou respiratoires", p: "Organiser une formation annuelle sur les risques chimiques et les bonnes pratiques de manipulation" },
      { q: "Les mains des salaries sont-elles protegees par une creme barriere avant le port des gants ?", d: "Risque de fragilisation cutanee par le contact repete avec des produits chimiques et l'eau", p: "Mettre a disposition des cremes barriere et des cremes reparatrices et encourager leur utilisation" },
    ]},
    { module: "Amenagement du salon", questions: [
      { q: "Les postes de travail sont-ils organises pour eviter les deplacements inutiles entre les differentes zones ?", d: "Risque de fatigue excessive et de TMS par des deplacements repetes", p: "Reorganiser le salon avec les zones shampooing, coupe et technique accessibles de maniere fluide" },
      { q: "Les bacs de lavage sont-ils ergonomiques avec un reglage en hauteur et une assise confortable pour le client ?", d: "Risque de lombalgies et de douleurs cervicales pour le coiffeur", p: "Installer des bacs de lavage basculants avec reglage en hauteur et repose-pieds" },
      { q: "Les sols du salon sont-ils faciles a nettoyer, antiderapants et en bon etat ?", d: "Risque de glissade sur des cheveux ou des produits renverses", p: "Installer un revetement de sol antiderapant et nettoyer regulierement les cheveux au sol" },
      { q: "L'eclairage du salon est-il suffisant et adapte pour les differentes zones de travail ?", d: "Risque de fatigue visuelle et d'erreurs dans les prestations", p: "Installer un eclairage de 500 lux minimum aux postes de coupe et un eclairage naturel complement" },
      { q: "Les miroirs et plans de travail sont-ils installes a une hauteur adaptee pour travailler sans se pencher ?", d: "Risque de postures penibles par un mobilier inadapte", p: "Ajuster la hauteur des plans de travail en fonction de la taille des coiffeurs" },
    ]},
    { module: "Postures et ergonomie", questions: [
      { q: "Les coiffeurs disposent-ils de tabourets a roulettes reglables en hauteur pour certaines prestations ?", d: "Risque de lombalgies et de varices par la station debout prolongee", p: "Fournir des tabourets ergonomiques a roulettes et encourager l'alternance assis-debout" },
      { q: "Les coiffeurs ont-ils ete sensibilises aux postures de travail pour limiter les douleurs aux epaules et au dos ?", d: "Risque de TMS par des gestes repetitifs les bras en elevation", p: "Former les coiffeurs aux postures de travail et proposer des exercices d'etirement" },
      { q: "Les ciseaux et outils sont-ils ergonomiques et adaptes a la morphologie de la main de chaque coiffeur ?", d: "Risque de tendinite et de syndrome du canal carpien", p: "Proposer des ciseaux ergonomiques avec des anneaux adaptes et des repose-doigts" },
      { q: "Des pauses regulieres sont-elles prevues pour permettre aux coiffeurs de se reposer et de s'etirer ?", d: "Risque d'accumulation de fatigue musculaire et de TMS", p: "Planifier des pauses de 10 minutes toutes les 2 heures et proposer des exercices de stretching" },
      { q: "Les sechoirs a main sont-ils legers et ergonomiques pour limiter la fatigue du bras et du poignet ?", d: "Risque de tendinite de l'epaule et du poignet par l'utilisation prolongee d'un sechoir lourd", p: "Choisir des sechoirs de moins de 500 grammes avec une poignee ergonomique" },
    ]},
    { module: "Equipements electriques et thermiques", questions: [
      { q: "Les appareils electriques (sechoirs, fers, lisseurs) sont-ils verifies regulierement et en bon etat ?", d: "Risque d'electrocution ou de brulure par un appareil defectueux", p: "Controler visuellement les appareils chaque semaine et faire verifier l'installation electrique annuellement" },
      { q: "Les fers a lisser et a boucler sont-ils poses sur des supports thermiques adaptes apres utilisation ?", d: "Risque de brulure par contact avec un appareil chaud pose sur le plan de travail", p: "Installer des supports thermiques a chaque poste et former le personnel a leur utilisation" },
      { q: "Les fils electriques des appareils sont-ils en bon etat, sans denudement ni raccord artisanal ?", d: "Risque d'electrocution par un fil endommage", p: "Remplacer immediatement les appareils dont le fil est endommage et interdire les reparations artisanales" },
      { q: "Les prises electriques du salon sont-elles equipees de dispositifs differentiels de protection ?", d: "Risque d'electrocution dans un environnement humide", p: "Installer des disjoncteurs differentiels 30 mA sur tous les circuits du salon" },
    ]},
    { module: "Risques biologiques", questions: [
      { q: "Les outils coupants (ciseaux, rasoirs) sont-ils desinfectes entre chaque client ?", d: "Risque de transmission d'infections (hepatites, mycoses) par des outils contamines", p: "Mettre en place un protocole de desinfection des outils avec un produit bactericide et virucide" },
      { q: "Un protocole est-il prevu en cas de coupure accidentelle d'un coiffeur ou d'un client ?", d: "Risque de contamination par le sang (AES)", p: "Former le personnel a la conduite a tenir en cas de coupure et disposer d'une trousse de premiers soins" },
      { q: "Les serviettes et peignoirs sont-ils laves a haute temperature entre chaque client ?", d: "Risque de transmission de mycoses et d'infections cutanees", p: "Laver les textiles a 60 degres minimum et utiliser un agent desinfectant dans le cycle de lavage" },
      { q: "Les bacs de lavage et les ustensiles sont-ils nettoyes et desinfectes quotidiennement ?", d: "Risque de proliferation de germes dans un environnement humide", p: "Nettoyer et desinfecter les bacs de lavage apres chaque service et les ustensiles entre chaque client" },
    ]},
    { module: "Risques psychosociaux", questions: [
      { q: "Les coiffeurs sont-ils exposes a des exigences emotionnelles liees a la relation avec les clients ?", d: "Risque de burn-out et de fatigue emotionnelle", p: "Former les coiffeurs a la gestion des relations clients difficiles et proposer des espaces d'echange" },
      { q: "La charge de travail est-elle adaptee au nombre de coiffeurs presents dans le salon ?", d: "Risque de stress et de precipitation source d'accidents", p: "Adapter les plannings de rendez-vous au nombre de coiffeurs disponibles" },
      { q: "Les salaries ont-ils la possibilite de signaler des situations de mal-etre au travail ?", d: "Risque de souffrance psychologique non prise en charge", p: "Mettre en place un referent RPS et organiser des entretiens individuels reguliers" },
      { q: "Les horaires de travail sont-ils compatibles avec une vie personnelle equilibree ?", d: "Risque de desequilibre vie professionnelle / vie personnelle", p: "Respecter les temps de repos et permettre une certaine flexibilite dans les horaires" },
    ]},
    { module: "Incendie et securite", questions: [
      { q: "Le salon dispose-t-il d'extincteurs adaptes et accessibles, notamment pres des zones de stockage de produits ?", d: "Risque de propagation d'un incendie en l'absence de moyen d'extinction", p: "Installer des extincteurs CO2 et eau pulverisee et les faire verifier annuellement" },
      { q: "Les issues de secours du salon sont-elles degagees et signalees ?", d: "Risque de blocage lors d'une evacuation", p: "Verifier quotidiennement le degagement des issues et installer une signaletique conforme" },
      { q: "La trousse de premiers secours est-elle complete, accessible et regulierement verifiee ?", d: "Risque de ne pas pouvoir prodiguer les premiers soins en cas d'accident", p: "Verifier mensuellement le contenu de la trousse et former au moins un salarie aux gestes de premiers secours" },
    ]},
    { module: "Ventilation et qualite de l'air", questions: [
      { q: "Le salon dispose-t-il d'un systeme de ventilation mecanique efficace pour evacuer les vapeurs chimiques ?", d: "Risque d'intoxication chronique par inhalation de vapeurs de produits capillaires", p: "Installer une VMC adaptee au volume du salon et au nombre de postes de travail" },
      { q: "Les zones de preparation des melanges chimiques sont-elles equipees d'une aspiration localisee ?", d: "Risque d'inhalation de poudres et de vapeurs concentrees", p: "Installer une hotte aspirante ou un bras d'aspiration au poste de preparation" },
      { q: "Le systeme de ventilation est-il entretenu et les filtres remplaces regulierement ?", d: "Risque de perte d'efficacite de la ventilation et d'accumulation de polluants", p: "Faire entretenir le systeme de ventilation chaque annee et remplacer les filtres selon les recommandations" },
      { q: "La qualite de l'air du salon est-elle mesuree periodiquement (ammoniac, COV, poussieres) ?", d: "Risque d'exposition chronique a des polluants sans le savoir", p: "Faire realiser des mesures de qualite de l'air par un organisme specialise au moins une fois par an" },
    ]},
  ],

  outil70: [
    { module: "Four et equipements de cuisson", questions: [
      { q: "Les fours sont-ils equipes de portes isolantes pour limiter les brulures par contact ?", d: "Risque de brulures graves par contact avec les surfaces chaudes du four", p: "Installer des fours avec portes a double vitrage isolant et verifier regulierement l'etancheite" },
      { q: "Les salaries portent-ils des gants et des manchettes anti-chaleur lors de l'enfournement et du defournement ?", d: "Risque de brulures aux mains et aux avant-bras", p: "Fournir des gants anti-chaleur adaptes et en imposer le port pour toute manipulation au four" },
      { q: "Les fourneaux et fours sont-ils entretenus et verifies regulierement par un professionnel ?", d: "Risque de dysfonctionnement pouvant provoquer un incendie ou une explosion de gaz", p: "Planifier une maintenance preventive semestrielle et verifier les raccordements gaz" },
      { q: "Les procedures d'allumage et d'extinction des fours a gaz sont-elles connues et appliquees ?", d: "Risque d'explosion par accumulation de gaz non enflamme", p: "Afficher les procedures d'allumage pres de chaque four et former le personnel a leur application" },
      { q: "Les tapis de four et les plaques de cuisson sont-ils manipules avec des outils adaptes ?", d: "Risque de brulures et de chute de plaques brulantes", p: "Utiliser des enfourneurs a manche long et des gants isolants pour manipuler les plaques" },
    ]},
    { module: "Petrissage et machines", questions: [
      { q: "Les petrins sont-ils equipes de grilles de protection empechant l'acces a la cuve en fonctionnement ?", d: "Risque de happement des mains ou des vetements par les organes en mouvement", p: "Verifier la presence et le bon etat des grilles de protection et interdire toute intervention sur le petrin en marche" },
      { q: "Les machines (diviseuse, bouleuse, faconneuse, laminoir) disposent-elles d'arrets d'urgence accessibles ?", d: "Risque de blessure grave en cas de blocage ou de happement", p: "Verifier mensuellement le fonctionnement des arrets d'urgence et les rendre facilement accessibles" },
      { q: "Les salaries ont-ils recu une formation a l'utilisation securisee de chaque machine ?", d: "Risque d'accident par meconnaissance du fonctionnement des machines", p: "Former chaque nouvel employe et organiser des rappels annuels sur l'utilisation des machines" },
      { q: "Les operations de nettoyage des machines sont-elles realisees machine arretee et consignee ?", d: "Risque de remise en marche accidentelle pendant le nettoyage", p: "Mettre en place une procedure de consignation et former le personnel a son application" },
      { q: "Les transmissions et parties mobiles des machines sont-elles protegees par des carters fixes ?", d: "Risque de contact avec les engrenages, courroies ou arbres en rotation", p: "Verifier la presence de tous les carters et interdire l'utilisation d'une machine sans protection" },
    ]},
    { module: "Manutention des farines", questions: [
      { q: "Les sacs de farine sont-ils stockes a une hauteur ergonomique pour limiter les efforts de portage ?", d: "Risque de lombalgies par le port de sacs de 25 kg ou plus", p: "Stocker les sacs a hauteur de travail et utiliser un elevateur ou un basculeur de sacs" },
      { q: "Des aides mecaniques (chariots, basculeurs, aspirateurs de farine) sont-elles disponibles ?", d: "Risque de TMS par la manutention repetee de charges lourdes", p: "Mettre a disposition des chariots et des basculeurs de sacs pour alimenter les petrins" },
      { q: "Les salaries sont-ils formes aux gestes et postures pour le transport et le versement des sacs de farine ?", d: "Risque de blessures dorsales par des gestes inadaptes", p: "Organiser une formation gestes et postures specifique a la manutention des farines" },
      { q: "Les sacs de farine sont-ils ouverts avec un outil adapte pour eviter la dispersion de poussiere ?", d: "Risque d'inhalation de poussiere de farine (asthme du boulanger)", p: "Utiliser un coupe-sac et verser la farine doucement pour limiter la mise en suspension" },
      { q: "Le local de stockage des farines est-il propre, sec et ventile pour eviter la proliferation d'insectes ?", d: "Risque de contamination des farines par des nuisibles", p: "Nettoyer regulierement le local, installer des grilles anti-insectes et controler les stocks" },
    ]},
    { module: "Risques chimiques et allergenes", questions: [
      { q: "Les produits de nettoyage du fournil sont-ils compatibles avec un usage alimentaire et correctement etiquetes ?", d: "Risque de contamination des denrees par des residus de produits chimiques", p: "Utiliser exclusivement des produits de nettoyage agrees contact alimentaire et respecter les dosages" },
      { q: "Les salaries sont-ils informes des risques lies a l'exposition aux poussieres de farine ?", d: "Risque d'asthme professionnel et de rhinite allergique", p: "Informer sur les risques respiratoires et assurer un suivi medical renforce pour les salaries exposes" },
      { q: "Un dispositif de captage des poussieres est-il installe au niveau des petrins et des zones de facade ?", d: "Risque d'inhalation de poussieres de farine en concentration elevee", p: "Installer des hottes aspirantes ou un systeme de captage a la source sur les postes emissifs" },
      { q: "Les allergenes presents dans les produits fabriques sont-ils identifies et traces tout au long de la fabrication ?", d: "Risque de presence non declaree d'allergenes (gluten, oeufs, lait, fruits a coque)", p: "Mettre en place un systeme de tracabilite des allergenes et former le personnel a la gestion des allergenes" },
    ]},
    { module: "Ambiance thermique", questions: [
      { q: "Des mesures sont-elles prises pour limiter la chaleur au poste de travail pres des fours ?", d: "Risque de coup de chaleur et de malaise par exposition a des temperatures elevees", p: "Installer des ecrans thermiques devant les fours et assurer une ventilation efficace du fournil" },
      { q: "De l'eau fraiche est-elle mise a disposition en permanence pour les salaries exposes a la chaleur ?", d: "Risque de deshydratation lors du travail en ambiance chaude", p: "Installer des fontaines a eau dans le fournil et encourager l'hydratation reguliere" },
      { q: "Les salaries alternent-ils entre les postes chauds et les postes froids pour limiter l'exposition thermique ?", d: "Risque de stress thermique par exposition prolongee a la chaleur", p: "Organiser une rotation des postes et des pauses dans un local rafraichi" },
      { q: "Les vetements de travail sont-ils adaptes a l'ambiance thermique du fournil ?", d: "Risque d'inconfort et de sudation excessive", p: "Fournir des tenues en coton leger et absorbant et prevoir des tenues de rechange" },
      { q: "La ventilation du fournil est-elle dimensionnee pour compenser la chaleur degagee par les fours ?", d: "Risque de temperature ambiante excessive dans le local de travail", p: "Faire verifier le dimensionnement de la ventilation par un bureau d'etudes et l'adapter si necessaire" },
    ]},
    { module: "Risques biologiques", questions: [
      { q: "Les surfaces de travail et les ustensiles sont-ils nettoyes et desinfectes selon un plan de nettoyage defini ?", d: "Risque de contamination microbiologique des produits fabriques", p: "Elaborer un plan de nettoyage-desinfection avec frequences et produits et en verifier l'application" },
      { q: "Les nuisibles (rongeurs, insectes) font-ils l'objet d'un plan de lutte et d'un suivi regulier ?", d: "Risque de contamination des matieres premieres et des produits finis", p: "Mettre en place un contrat avec une societe specialisee et verifier mensuellement les postes d'appats" },
      { q: "Les salaries respectent-ils les regles d'hygiene personnelle (lavage des mains, tenue propre, coiffe) ?", d: "Risque de contamination des produits par les manipulations", p: "Former les salaries aux bonnes pratiques d'hygiene et mettre a disposition des lave-mains a commande non manuelle" },
      { q: "Les matieres premieres perissables sont-elles stockees dans des conditions de temperature adaptees ?", d: "Risque de developpement de micro-organismes pathogenes", p: "Controler et enregistrer les temperatures des enceintes frigorifiques deux fois par jour" },
    ]},
    { module: "Organisation du travail", questions: [
      { q: "Les horaires de travail de nuit sont-ils organises pour limiter la fatigue et les risques associes ?", d: "Risque de troubles du sommeil, de fatigue chronique et d'accidents lies au travail de nuit", p: "Limiter les amplitudes horaires, prevoir des temps de repos et proposer un suivi medical renforce" },
      { q: "Les pauses sont-elles amenagees avec un espace de repos confortable a l'ecart du fournil ?", d: "Risque de fatigue excessive par manque de recuperation", p: "Amenager un local de repos climatise avec mobilier confortable et acces a des boissons" },
      { q: "Le travail isole la nuit est-il pris en compte avec des mesures de securite specifiques ?", d: "Risque de ne pas etre secouru rapidement en cas d'accident ou de malaise", p: "Mettre en place un systeme de ronde ou un dispositif d'alerte pour travailleur isole (PTI-DATI)" },
      { q: "Les nouveaux apprentis sont-ils encadres et formes aux risques specifiques du metier ?", d: "Risque d'accident par manque d'experience et de formation", p: "Designar un tuteur forme et organiser une formation securite avant la prise de poste" },
    ]},
    { module: "Incendie et electricite", questions: [
      { q: "Les installations electriques du fournil sont-elles adaptees a l'environnement (chaleur, humidite, farine) ?", d: "Risque d'incendie ou d'electrocution par des installations inadaptees", p: "Faire verifier les installations par un electricien qualifie et utiliser du materiel etanche" },
      { q: "Les extincteurs du fournil sont-ils adaptes aux risques presents (feu de gaz, feu electrique) ?", d: "Risque d'utilisation d'un extincteur inadapte aggravant la situation", p: "Installer des extincteurs CO2 pour les feux electriques et poudre pour les feux de gaz" },
      { q: "Les conduits d'evacuation des fumees et des buees sont-ils nettoyes regulierement ?", d: "Risque d'incendie par accumulation de depots dans les conduits", p: "Faire ramoner les conduits chaque annee et nettoyer les filtres des hottes mensuellement" },
      { q: "Le local de stockage des emballages et cartons est-il separe du fournil ?", d: "Risque de propagation rapide d'un incendie par les materiaux combustibles", p: "Stocker les cartons et emballages dans un local separe et limiter les quantites dans le fournil" },
    ]},
  ],

  outil71: [
    { module: "Machines de decoupe", questions: [
      { q: "Les scies a os et scies a ruban sont-elles equipees de protecteurs regles au plus pres de la piece a couper ?", d: "Risque de coupure grave ou d'amputation par la lame en mouvement", p: "Regler les protecteurs au plus pres de la viande et former le personnel au reglage correct" },
      { q: "Les dispositifs d'arret d'urgence des machines de decoupe sont-ils accessibles et testes regulierement ?", d: "Risque de blessure prolongee si la machine ne peut etre arretee rapidement", p: "Tester les arrets d'urgence chaque semaine et les positionner a portee de main de l'operateur" },
      { q: "Le hachoir est-il equipe d'un poussoir obligeant a eloigner la main de la vis sans fin ?", d: "Risque de happement de la main dans la vis du hachoir", p: "Utiliser systematiquement le poussoir fourni et interdire toute introduction manuelle" },
      { q: "Les machines sont-elles nettoyees uniquement apres arret complet et consignation ?", d: "Risque de demarrage accidentel pendant le nettoyage", p: "Appliquer une procedure de consignation avant toute intervention de nettoyage ou de maintenance" },
      { q: "Les lames des scies sont-elles changees par du personnel forme et avec des protections adaptees ?", d: "Risque de coupure lors du changement de lame", p: "Former le personnel au changement de lame et fournir des gants anti-coupure pour cette operation" },
    ]},
    { module: "Outils tranchants", questions: [
      { q: "Les couteaux et feuilles de boucher sont-ils ranges dans des etuis ou sur des supports magnetiques ?", d: "Risque de coupure par des couteaux laisses sur le plan de travail ou dans un bac", p: "Installer des porte-couteaux magnetiques et interdire de laisser les couteaux dans les bacs de lavage" },
      { q: "Les salaries portent-ils un tablier de protection en maille metallique lors des operations de desossage ?", d: "Risque de perforation abdominale par derape du couteau", p: "Fournir des tabliers en cotte de mailles et en imposer le port lors du desossage" },
      { q: "Les salaries portent-ils un gant en maille metallique sur la main qui ne tient pas le couteau ?", d: "Risque de coupure de la main d'appui lors de la decoupe", p: "Fournir des gants en cotte de mailles adaptes et former a leur utilisation correcte" },
      { q: "Les couteaux sont-ils affutes regulierement pour eviter les efforts excessifs de coupe ?", d: "Risque de glissement de la lame par effort excessif sur un couteau emousse", p: "Affuter les couteaux quotidiennement et former le personnel aux techniques d'affutage securisees" },
      { q: "Les postes de decoupe sont-ils stables, a la bonne hauteur et equipes de planches de decoupe fixees ?", d: "Risque de glissement de la planche ou de posture penible", p: "Utiliser des billots stables a hauteur adaptee et des planches avec dispositif anti-glissement" },
    ]},
    { module: "Chambres froides", questions: [
      { q: "Les chambres froides positives et negatives sont-elles equipees d'un systeme d'ouverture interieure et d'une alarme ?", d: "Risque d'enfermement accidentel dans le froid pouvant entrainer une hypothermie", p: "Verifier mensuellement le systeme d'ouverture interieure, l'alarme et le voyant lumineux exterieur" },
      { q: "Les sols des chambres froides sont-ils antiderapants et en bon etat ?", d: "Risque de chute par glissade sur des sols givres ou mouilles", p: "Installer des revetements antiderapants et nettoyer regulierement le givre au sol" },
      { q: "Les salaries travaillant en chambre froide negative disposent-ils de vetements isolants adaptes ?", d: "Risque de gelures et d'hypothermie par exposition prolongee au froid", p: "Fournir des vetements isolants (veste, pantalon, gants, bonnet) adaptes aux temperatures negatives" },
      { q: "La duree de presence en chambre froide negative est-elle limitee avec des periodes de rechauffement ?", d: "Risque d'hypothermie par une exposition prolongee au froid extreme", p: "Limiter les sessions de travail en froid negatif et prevoir des pauses rechauffement dans un local tempere" },
      { q: "Les denrees sont-elles rangees de maniere ordonnee pour faciliter l'acces et limiter le temps passe dans le froid ?", d: "Risque d'exposition prolongee au froid lors de la recherche de produits", p: "Organiser le rangement avec un plan de stockage clair et un etiquetage visible" },
    ]},
    { module: "Manutention des carcasses", questions: [
      { q: "Des rails aeriens et des palans sont-ils installes pour le transport des carcasses et des pieces de viande lourdes ?", d: "Risque de lombalgies et de blessures par le port de charges lourdes (carcasses de 80 a 150 kg)", p: "Installer des rails de manutention aeriens et des palans pour le deplacement des carcasses" },
      { q: "Les crochets et les rails de suspension sont-ils verifies regulierement pour leur solidite ?", d: "Risque de chute de carcasse sur le personnel", p: "Faire verifier les installations de suspension chaque trimestre et remplacer les crochets uses" },
      { q: "Les salaries sont-ils formes aux techniques de manutention des pieces de viande lourdes ?", d: "Risque de TMS par des techniques de portage inadaptees", p: "Former le personnel aux gestes et postures et utiliser des aides a la manutention (chariots, crochets)" },
      { q: "Les quais de reception des carcasses sont-ils equipes pour faciliter le dechargement des camions ?", d: "Risque de chute et de blessure lors du dechargement de pieces lourdes", p: "Installer un quai de dechargement a hauteur et des rampes d'acces pour les chariots" },
      { q: "Des chariots a viande sont-ils disponibles pour le transport des pieces de la chambre froide au poste de decoupe ?", d: "Risque de TMS par le port repete de pieces de viande", p: "Mettre a disposition des chariots inox a roulettes en nombre suffisant" },
    ]},
    { module: "Hygiene et risques biologiques", questions: [
      { q: "Les salaries respectent-ils les regles de lavage et de desinfection des mains entre chaque tache ?", d: "Risque de contamination croisee et de toxi-infections alimentaires", p: "Installer des lave-mains a commande non manuelle et afficher les consignes de lavage" },
      { q: "Les surfaces de travail (billots, plans de decoupe, machines) sont-elles nettoyees et desinfectees apres chaque utilisation ?", d: "Risque de proliferation bacterienne sur les surfaces en contact avec la viande", p: "Appliquer un protocole de nettoyage-desinfection apres chaque operation et verifier par des prelevements" },
      { q: "Les dechets organiques (os, chutes, graisse) sont-ils evacues rapidement dans des conteneurs fermes ?", d: "Risque de proliferation bacterienne et d'attraction de nuisibles", p: "Evacuer les dechets dans des conteneurs etanches et les stocker en chambre froide avant enlevement" },
      { q: "Les tenues de travail sont-elles changees quotidiennement et lavees a haute temperature ?", d: "Risque de contamination des produits par des tenues souillees", p: "Fournir des tenues propres chaque jour et les laver a 60 degres minimum" },
      { q: "Un plan de lutte contre les nuisibles est-il en place et suivi regulierement ?", d: "Risque de contamination des viandes par des rongeurs ou des insectes", p: "Mettre en place un contrat avec un prestataire de desinsectisation-deratisation et verifier mensuellement" },
    ]},
    { module: "Risques chimiques", questions: [
      { q: "Les produits de nettoyage et de desinfection utilises sont-ils agrees pour le contact alimentaire ?", d: "Risque de contamination chimique des denrees alimentaires", p: "Utiliser uniquement des produits agrees contact alimentaire et respecter les concentrations prescrites" },
      { q: "Les salaries sont-ils formes a l'utilisation correcte des produits de nettoyage et de desinfection ?", d: "Risque de brulures chimiques ou d'intoxication par mauvaise utilisation", p: "Former le personnel aux bonnes pratiques d'utilisation et afficher les consignes de dosage" },
      { q: "Les produits chimiques sont-ils stockes separement des denrees alimentaires ?", d: "Risque de contamination accidentelle des aliments par des produits chimiques", p: "Stocker les produits chimiques dans un local ferme et separe de la zone de production" },
      { q: "Les salaries portent-ils des EPI lors de la manipulation de produits concentres (gants, lunettes) ?", d: "Risque de brulures cutanees ou oculaires par contact avec des produits concentres", p: "Fournir des gants et des lunettes de protection et en imposer le port lors de la preparation des solutions" },
    ]},
    { module: "Sols et circulation", questions: [
      { q: "Les sols de l'atelier de decoupe sont-ils antiderapants et nettoyes regulierement ?", d: "Risque de glissade sur des sols mouilles, gras ou souilles de sang", p: "Installer des revetements antiderapants et nettoyer les sols plusieurs fois par jour" },
      { q: "Les zones de circulation sont-elles balisees et separees des zones de travail ?", d: "Risque de collision entre les personnes et les chariots en deplacement", p: "Baliser les zones de circulation au sol et definir des sens de deplacement" },
      { q: "Les caniveaux et siphons de sol sont-ils en bon etat et nettoyes regulierement ?", d: "Risque de stagnation d'eau au sol et de glissade", p: "Verifier le bon ecoulement des eaux et nettoyer les caniveaux quotidiennement" },
      { q: "Les salaries portent-ils des chaussures de securite antiderapantes et impermeables ?", d: "Risque de glissade et de blessure aux pieds par des chutes d'objets", p: "Fournir des bottes de securite antiderapantes certifiees S3 et verifier leur etat regulierement" },
    ]},
    { module: "Organisation du travail", questions: [
      { q: "Les horaires matinaux sont-ils organises pour permettre un temps de repos suffisant entre deux journees ?", d: "Risque de fatigue chronique et de troubles du sommeil", p: "Respecter un minimum de 11 heures de repos entre deux journees et organiser les plannings en consequence" },
      { q: "Le document unique d'evaluation des risques est-il a jour et prend-il en compte les specificites du metier ?", d: "Meconnaissance des risques actuels et non-conformite reglementaire", p: "Mettre a jour le DUERP chaque annee en y integrant les risques specifiques de la boucherie" },
      { q: "Les apprentis et les nouveaux employes beneficient-ils d'un tutorat et d'une formation securite ?", d: "Risque d'accident par manque de formation et d'experience", p: "Designar un tuteur qualifie et organiser une formation securite complete avant la prise de poste" },
      { q: "Un registre des accidents du travail et des presqu'accidents est-il tenu et analyse ?", d: "Risque de repetition des accidents par absence de retour d'experience", p: "Tenir un registre a jour et analyser chaque incident pour mettre en place des actions correctives" },
    ]},
  ],

  outil68: [
    { module: "Deplacements et risques routiers", questions: [
      { q: "Les salaries sont-ils sensibilises aux risques routiers lies aux deplacements entre les domiciles des beneficiaires ?", d: "Risque d'accident de la route, premiere cause de mortalite au travail", p: "Organiser des sessions de sensibilisation au risque routier et planifier les tournees pour limiter les kilometres" },
      { q: "Les vehicules utilises pour les deplacements professionnels sont-ils entretenus et equipes pour la securite ?", d: "Risque d'accident par defaut d'entretien du vehicule", p: "Mettre en place un carnet d'entretien du vehicule et verifier regulierement pneumatiques, freins et eclairage" },
      { q: "Les plannings de tournees sont-ils organises pour eviter les temps de trajet excessifs et la precipitation ?", d: "Risque d'accident routier par fatigue ou precipitation entre deux interventions", p: "Optimiser les tournees geographiquement et prevoir des temps de trajet suffisants entre les interventions" },
      { q: "Les salaries disposent-ils d'un kit de securite dans leur vehicule (gilet, triangle, trousse de secours) ?", d: "Risque de sur-accident en cas de panne ou d'accident sur la route", p: "Fournir un kit de securite routiere et verifier son contenu chaque annee" },
      { q: "Les conditions meteorologiques defavorables sont-elles prises en compte dans l'organisation des tournees ?", d: "Risque accru d'accident en cas de verglas, neige ou fortes pluies", p: "Prevoir un protocole d'adaptation des tournees en cas de conditions meteorologiques degradees" },
    ]},
    { module: "Manutention des personnes", questions: [
      { q: "Les salaries ont-ils recu une formation aux techniques de transfert et de mobilisation des personnes aidees ?", d: "Risque de lombalgies et de TMS par des gestes de manutention inadaptes", p: "Organiser une formation initiale et des recyclages annuels aux techniques de mobilisation des personnes" },
      { q: "Des aides techniques (leve-personne, draps de glisse, ceinture de transfert) sont-elles disponibles au domicile ?", d: "Risque de TMS par l'absence d'aides a la manutention", p: "Evaluer les besoins en aides techniques et en recommander l'acquisition au beneficiaire ou a la famille" },
      { q: "Le lit du beneficiaire est-il a hauteur variable pour faciliter les soins et la toilette ?", d: "Risque de lombalgies par des postures penibles au lit", p: "Recommander l'installation d'un lit medicalise a hauteur variable et former les salaries a son utilisation" },
      { q: "Les transferts de personnes sont-ils realises a deux lorsque le poids ou l'etat du beneficiaire le necessitent ?", d: "Risque de chute du beneficiaire et de blessure de l'intervenant", p: "Organiser les interventions en binome pour les transferts de personnes dependantes" },
      { q: "L'etat de sante du beneficiaire est-il reevalue regulierement pour adapter les techniques de manutention ?", d: "Risque d'utiliser des techniques inadaptees a l'evolution de l'etat du beneficiaire", p: "Mettre en place une fiche de liaison et reevaluer les besoins a chaque changement d'etat" },
    ]},
    { module: "Risques au domicile", questions: [
      { q: "Une evaluation des risques au domicile du beneficiaire est-elle realisee avant le debut de l'intervention ?", d: "Risque d'accident dans un environnement non maitrise par l'employeur", p: "Realiser une visite prealable du domicile pour identifier les dangers et consigner les observations" },
      { q: "Les sols du domicile presentent-ils des risques de chute (tapis, cables, encombrement, mauvais eclairage) ?", d: "Risque de chute de plain-pied dans un environnement souvent inadapte", p: "Proposer des amenagements au beneficiaire (retrait des tapis, fixation des cables, amelioration de l'eclairage)" },
      { q: "Les escaliers du domicile sont-ils equipes de mains courantes et d'un eclairage suffisant ?", d: "Risque de chute dans les escaliers mal equipes", p: "Recommander l'installation de mains courantes et d'un eclairage automatique dans les escaliers" },
      { q: "La salle de bain du beneficiaire est-elle equipee de barres d'appui et d'un tapis antiderapant ?", d: "Risque de chute dans un environnement mouille et exigu", p: "Proposer l'installation de barres d'appui, d'un siege de douche et d'un tapis antiderapant" },
      { q: "Les installations electriques et de gaz du domicile sont-elles en bon etat apparent ?", d: "Risque d'electrocution ou d'explosion de gaz", p: "Signaler tout defaut apparent a l'employeur et au beneficiaire et refuser d'intervenir en cas de danger grave" },
    ]},
    { module: "Risques chimiques menagers", questions: [
      { q: "Les salaries sont-ils informes des risques lies aux produits menagers qu'ils utilisent au domicile ?", d: "Risque d'intoxication ou de brulure chimique par des produits menagers", p: "Former les salaries aux risques des produits menagers courants et fournir une fiche de recommandations" },
      { q: "Les salaries evitent-ils de melanger differents produits menagers (javel et detartrant par exemple) ?", d: "Risque de degagement de gaz toxiques par melange de produits incompatibles", p: "Former les salaries aux incompatibilites de produits et interdire les melanges" },
      { q: "Des gants de menage sont-ils portes lors de l'utilisation de produits d'entretien ?", d: "Risque de dermatite de contact et d'allergie cutanee", p: "Fournir des gants de menage adaptes et en imposer le port lors de toute utilisation de produits chimiques" },
      { q: "Les produits menagers au domicile sont-ils correctement etiquetes et stockes hors de portee des enfants ?", d: "Risque d'ingestion accidentelle ou de confusion de produits", p: "Verifier l'etiquetage des produits et signaler les stockages dangereux au beneficiaire" },
      { q: "Les locaux sont-ils suffisamment ventiles lors de l'utilisation de produits volatils ?", d: "Risque d'inhalation de vapeurs irritantes ou toxiques", p: "Ouvrir les fenetres lors de l'utilisation de produits de nettoyage et eviter les produits en aerosol" },
    ]},
    { module: "Risques biologiques", questions: [
      { q: "Les salaries sont-ils formes aux precautions standard pour la prevention des risques infectieux ?", d: "Risque de contamination par des agents biologiques (bacteries, virus) lors des soins", p: "Former les salaries aux precautions standard et fournir des gants a usage unique" },
      { q: "Des gants a usage unique sont-ils disponibles et utilises pour les soins d'hygiene des beneficiaires ?", d: "Risque de contamination par contact avec des liquides biologiques", p: "Fournir des gants en quantite suffisante et former a leur utilisation correcte" },
      { q: "Les salaries sont-ils vaccines contre les risques infectieux lies a leur activite (grippe, hepatite B) ?", d: "Risque de contamination par des pathogenes transmissibles", p: "Proposer les vaccinations recommandees et assurer le suivi du calendrier vaccinal" },
      { q: "Un protocole de conduite a tenir en cas d'accident d'exposition au sang est-il connu des salaries ?", d: "Risque de contamination par le sang ou les liquides biologiques en cas de coupure ou de projection", p: "Former les salaries au protocole AES et afficher les numeros d'urgence a contacter" },
    ]},
    { module: "Risques psychosociaux", questions: [
      { q: "Les salaries beneficient-ils d'un soutien psychologique pour faire face aux situations emotionnellement difficiles ?", d: "Risque de burn-out et de traumatisme par la confrontation a la souffrance et a la fin de vie", p: "Mettre en place des groupes de parole et un acces a un psychologue du travail" },
      { q: "Les situations de violence ou d'agressivite de la part des beneficiaires ou de leur entourage sont-elles prises en charge ?", d: "Risque d'agression physique ou verbale lors des interventions a domicile", p: "Mettre en place un protocole de signalement et d'accompagnement des salaries victimes" },
      { q: "Les salaries sont-ils prepares a la gestion de situations de deces ou de fin de vie des beneficiaires ?", d: "Risque de souffrance psychologique par l'attachement au beneficiaire", p: "Former les salaries a l'accompagnement de fin de vie et proposer un debriefing apres un deces" },
      { q: "La reconnaissance du travail des aides a domicile est-elle assuree par l'encadrement ?", d: "Risque de perte de motivation et de sentiment de devalorisation", p: "Organiser des entretiens d'evaluation reguliers et valoriser les competences des salaries" },
      { q: "Les salaries ont-ils des espaces d'echange collectif pour partager leurs difficultes professionnelles ?", d: "Risque d'isolement et de sentiment d'abandon", p: "Organiser des reunions d'equipe mensuelles et des temps de partage de pratiques" },
    ]},
    { module: "Travail isole", questions: [
      { q: "Les salaries travaillant seuls au domicile disposent-ils d'un dispositif d'alerte en cas de malaise ou d'agression ?", d: "Risque de ne pas etre secouru rapidement en cas de probleme", p: "Equiper les salaries d'un dispositif PTI-DATI (protection du travailleur isole) avec alerte automatique" },
      { q: "Les salaries connaissent-ils les numeros d'urgence et la conduite a tenir en cas de probleme au domicile ?", d: "Risque de perte de temps en cas de situation d'urgence", p: "Former les salaries aux gestes de premiers secours et afficher les numeros d'urgence sur leur telephone" },
      { q: "L'employeur est-il informe en temps reel de la localisation de ses salaries en intervention ?", d: "Risque de ne pas savoir ou se trouve un salarie en cas de non-reponse", p: "Mettre en place un systeme de pointage telephonique en debut et fin d'intervention" },
      { q: "Un protocole est-il prevu pour les interventions chez des beneficiaires identifies comme pouvant presenter un risque ?", d: "Risque d'agression ou de situation dangereuse chez certains beneficiaires", p: "Evaluer les risques lies a chaque beneficiaire et prevoir des interventions en binome si necessaire" },
    ]},
    { module: "Organisation des interventions", questions: [
      { q: "Les plannings d'intervention laissent-ils des temps suffisants entre deux interventions pour les deplacements et la recuperation ?", d: "Risque de fatigue et de precipitation source d'accidents", p: "Prevoir un temps de battement d'au moins 15 minutes entre deux interventions" },
      { q: "Les salaries sont-ils consultes lors de l'elaboration de leurs plannings de travail ?", d: "Risque de plannings inadaptes generant du stress et de la fatigue", p: "Associer les salaries a la construction des plannings et prendre en compte leurs contraintes" },
      { q: "Les fiches de liaison entre les intervenants successifs chez un meme beneficiaire sont-elles renseignees ?", d: "Risque de perte d'information sur l'etat du beneficiaire entre les intervenants", p: "Mettre en place un cahier de liaison au domicile et sensibiliser les salaries a son utilisation" },
      { q: "Les salaries disposent-ils du materiel necessaire pour realiser leurs interventions dans de bonnes conditions ?", d: "Risque d'utilisation de materiel inadapte ou defectueux au domicile", p: "Fournir un kit d'intervention avec les outils et les EPI necessaires et verifier regulierement son contenu" },
      { q: "Les horaires de travail respectent-ils les amplitudes maximales et les temps de repos reglementaires ?", d: "Risque de fatigue excessive par des amplitudes horaires trop importantes", p: "Controler les amplitudes horaires et respecter les 11 heures de repos quotidien minimum" },
    ]},
  ],
};
